# gormt 配置文件
# go get -u -v github.com/xxjwxc/gormt@master
# cd .; gormt
base:
    is_dev: false
db_info:
    host: localhost
    port: 3306
    username: root
    password: 228999
    database: order-food
    type: 0
out_dir: .
url_tag: json
language: English
db_tag: gorm
user_gorm_model: true
simple: true
is_web_tag: true
is_web_tag_pk_hidden: true
is_foreign_key: true
is_out_sql: true
is_out_func: true
is_gui: false
is_table_name: true
is_null_to_point: true
table_prefix: ""
self_type_define: {}
out_file_name: ""
web_tag_type: 0
table_names: ""
is_column_name: true
is_out_file_by_table_name: true
is_out_page: true
